---
- name: Ensure ~/.azure directory exists
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.azure"
    state: directory
    mode: "0700"

- name: Write openshift-install Azure service principal credentials
  ansible.builtin.template:
    src: osServicePrincipal.json.j2
    dest: "{{ lookup('env', 'HOME') }}/.azure/osServicePrincipal.json"
    mode: "0600"
  no_log: true
